### PR TITLE
Added some help text to specify that a default for the key is required

### PR DESCRIPTION
**Pull request by mikesir87**
Took me a while to figure it out, but a default for the key is required.  Updated the documentation to help express that.

### CODE REVIEW

**Comment by dhruvaray** [comment]
@mikesir87 : Here's a simple example to show that this should not be the case

``` javascript
Animal = Backbone.AssociatedModel.extend();
Owner = Backbone.AssociatedModel.extend();

House = Backbone.AssociatedModel.extend({
    relations: [
        {
            type: Backbone.One,
            key: 'owner',
            relatedModel: Owner     
        },
        {
            type: Backbone.Many,
            key: 'pets',
            relatedModel: Animal        
        }
    ]

});

var dog = new Animal({"name":"Lassy"});
var man = new Owner({"name":"Greg"});
var house  = new House({pets:[dog], owner:man});

console.log(house.get('owner.name') + " has a pet whose name is " + house.get('pets[0].name'));
//Greg has a pet whose name is Lassy
```

Am I understanding your problem right?

**Comment by mikesir87** [comment]
Yes, but I seem to be getting a better understanding of what the problem is.  It seems to be a problem only when using the **collectionType** key.  

When creating an AssociatedModel with a collectionType, the collection is not set on the key unless the key has a default value.  If you were using a collectionType without the defaultValue for your pets relation, your `house.get('pets')` would be `undefined`.

I made up an example webpage that demonstrates the two instances.  You can check it out here: http://irwinet.com/temp/backbone-associations/

So, maybe this actually isn't a documentation fix that's needed, but maybe a simple patch to the actual javascript. I've taken a look through it, but haven't nailed it down yet.

**Comment by dhruvaray** [comment]
@mikesir87 : It should not be an issue in this case too. See this example

``` javascript
Animal = Backbone.Model.extend();
Animals = Backbone.Collection.extend({model:Animal});
Owner = Backbone.Model.extend();

House = Backbone.AssociatedModel.extend({
    relations: [
        {
            type: Backbone.One,
            key: 'owner',
            relatedModel: Owner     
        },
        {
            type: Backbone.Many,
            key: 'pets',
            collectionType: Animals

        }
    ]
});

var dog = new Animal({"name":"Lassy"});
var man = new Owner({"name":"Greg"});
var house  = new House({pets:[dog], owner:man});

console.log(house.get('owner.name') + " has a pet whose name is " + house.get('pets[0].name'));
//Greg has a pet whose name is Lassy

```

I had a look at your site, Since pets is undefined, you can't do a fetch on that. You can do a fetch on the parent (House or Owner as the case may be) to fetch pets.

**Comment by mikesir87** [comment]
Yup. I know pets is undefined, which is the issue I'm running into.  I would expect that since I had set a relationship defined on that key, if I don't define it during construction of the model, it should create a collection for me to represent that collection.  

When I provide a default value for that key (even if it's just null), it does exactly what I'd expect and the collection does get created.  If there is no default value defined for the key, no collection is setup to represent that collection, hence why I'm getting undefined.  There's different behavior for the setup of the relationship based on if you provide a default value or not.

I also tried calling fetch on the parent, and nothing happened in either case.  I got an error stating that the parent doesn't have a url defined, even though I want to just fetch the children.

**Comment by dhruvaray** [comment]
@mikesir87 : Take a look at this [recipe](http://dhruvaray.github.io/backbone-associations/recipes.html#tut-savefetch) in our documentation. Here Department has no `locations` property defined. You can however yet fetch/save all the `locations` for that department. If you want to see/edit a running example, go to the jsfiddle behind this gist - [here](http://jsfiddle.net/jdkanani/a33Zt/)

**Comment by mikesir87** [comment]
I took a look, and the difference is that during the Department.fetch(), all of the children locations are provided.  I'd like to lazy fetch the children, rather than having to have them included in the initial fetch.

In order to do that lazy fetching, a collection must exist for the key.  When a default is defined in the model, that collection is created and setup.  If no default is provided, no collection is created.  No lazy fetching is allowed.

So, yes, the default isn't required in order to make the normal use case work, so my pull request isn't valid anymore.  But, in order to do lazy fetching and have a collection defined, a default for the key must exist.  Maybe a patch to the plugin could fix this?  Not sure, but I can look into it.

**Comment by dhruvaray** [comment]
I don't think this is a framework feature. It's far easier to let applications define properties as per their convenience. If you yet think you can submit something generic (and interesting), please do submit a fresh pull request.

I hope the example - provided earlier - helps you get going with your work!

**Comment by dhruvaray** [comment]
I am closing this issue... If you yet face a problem, do write back. Also, if you like our library, do show your appreciation by starring us!

**Pull request closed without merging**
