### PR TITLE
Feature/create custom collection method

### PR DESCRIPTION
**Pull request by g10**
Allow to customise the creation of a `collectionType` when subclassing the AssociatedModel. Functionality stays identical, but by extracting the creation of the collection to its own method, one can override this method when subclassing.

A possible use case is when one wants to pass `options` to the collectionType constructor, which must be available in the constructor, before the `initialize` method is called. 
_( specific use case: a dependency injector that needs to be passed from AssociatedModel → Collection → Model, with the `initialize` method the models in the collection are already constructed )_

### CODE REVIEW

**Comment by jdkanani** [comment]
Cool! It would be nice if you could change method name to `createCollection` (I usually use `_method` to denote internal/private method)

**Comment by g10** [comment]
IMHO I think this should be a private method which only should be able to be overwritten/extended by a subclass. Having `createCollection` as a public method would define its (possible) usage as `associatedModelInstance.createCollection()`, which is not the intention.
`_createCollectionTypeCollection` could be a more suitable naming though.

**Comment by janispauls** [comment]
Exactly what i was looking for. Lets hope it gets merged soon.

**Comment by dhruvaray** [comment]
@g10 : I am thinking that there is an easier way to achieve what you want... See this commit (and the associated test case) - d66904085b89ba8e558358cf958fef7f5332a938. Would this work for you?

**Comment by dhruvaray** [comment]
Updated commit to use a new property - `collectionOptions` to avoid confusion with the set related `options`

**Comment by g10** [comment]
@dhruvaray My first impression was that this would work, but unfortunately a quick test shows it does not.

What I notice is that the config object option does not allow to reference properties on the containing model, eg.

``` javascript
_myProperty: 'someValue',
relations: [
    {
        type: Backbone.Many,
        key: 'contextCollection',
        collectionType: ContextCollection,
        collectionOptions: {
            customProp: this._myProperty  // undefined, am I missing something here?
        }
    }
]
```

In contrast with providing a creation method, in line with [`Backbone.Collection::_prepareModel`](http://documentcloud.github.io/backbone/docs/backbone.html#section-112), which allows to override the creation method in a subclass, and **is able to pass the current state of a custom/complex property as an option** on creation.

**Comment by dhruvaray** [comment]
@g10 : I see what you are after... I have just re-factored the current `_createCollection` to be used in both the scenarios. See this commit - 99b485c3eb4cbfc9f3d03c9c454344856fa78d19. Tell me if this works for you.

**Comment by dhruvaray** [comment]
`collectionOptions` can also be a function which returns an options hash via commit - f33d69dfd742075f2e93ea6e5b589f40b78821e3

**Comment by g10** [comment]
:+1:  this works perfectly.
(and a nice refactor of that `_createCollection` method)

**Comment by dhruvaray** [comment]
Thanks!

**Pull request closed without merging**
