### PR TITLE
Cleanup dependencies

### PR DESCRIPTION
**Pull request by dak**
Remove underscore as a dependency, since it's a dependency of backbone,
and reconcile dependency versions for npm and bower.

### CODE REVIEW

**Comment by dhruvaray** [comment]
Thanks!

**Comment by johanneslumpe** [comment]
This is actually something that is now bugging me. As the underscore dependency of backbone is installed locally, it is not available to backbone-associations. If you compile the code with browserify it will be fine. But now running tests inside of node will just fail, because backbone-associations cannot find underscore anymore. I really don't want to add underscore as a top-level dependency.

Am I the only one doing testing in node and having this issue with the latest version? I could just add underscore back in, but I'd feel better if @dhruvaray or @jdkanani would share their thoughts about this :)

**Comment by jdkanani** [comment]
@johanneslumpe You are right. Backbone-associations cannot find `underscore` as It is local to backbone.

**Comment by jdkanani** [comment]
I have added underscore as dependency with commit 7f175593ea833f915bde207da8bc03381d9fb26e

**Comment by johanneslumpe** [comment]
@jdkanani cool! It is course only an issue if you want to run the code without browserifying it first.

**Comment by dhruvaray** [comment]
Pushed out v0.6.1 on npm...

**Pull request merged**
